name: Nestjs CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted
    environment: .env

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: use variables
        run: |
          echo "HOST : $HOST"
          echo "AUTH_PORT : $AUTH_PORT"
          echo "HOST_FONT : $HOST_FONT"
          echo "SERVER_MAIL : $SERVER_MAIL"
          echo "USER_MAIL : $USER_MAIL"
          echo "PASS_MAIL : $PASS_MAIL"
          echo "DB : $DB"
          echo "DB_HOST : $DB_HOST"
          echo "DB_PORT_AUTH : $DB_PORT_AUTH"
          echo "DB_DATABASE : $DB_DATABASE"
          echo "DB_USER : $DB_USER"
          echo "DB_PASS : $DB_PASS"
        env:
          HOST: ${{ vars.HOST }}
          AUTH_PORT: ${{ vars.AUTH_PORT }}
          HOST_FONT: ${{ vars.HOST_FONT }}
          SERVER_MAIL: ${{ vars.SERVER_MAIL }}
          USER_MAIL: ${{ vars.USER_MAIL }}
          PASS_MAIL: ${{ vars.PASS_MAIL }}
          DB: ${{ vars.DB }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT_AUTH: ${{ vars.DB_PORT_AUTH }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASS: ${{ vars.DB_PASS }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
      - run: npm run build
      - run: npm run lint-win
